import fs from 'fs';
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, query, where } from 'firebase/firestore';

const config = JSON.parse(fs.readFileSync('./firebase-applet-config.json', 'utf8'));
const app = initializeApp(config);
const db = getFirestore(app, config.firestoreDatabaseId);

async function run() {
  const q = query(collection(db, 'content'), where('contentType', '==', 'Question Bank'));
  const snapshot = await getDocs(q);
  
  let foundErrors = false;
  
  snapshot.forEach(doc => {
    const data = doc.data();
    const body = data.body || '';
    
    // Check if the HTML directly contains 'math input error' or similar things.
    // However, math input error is usually generated by MathJax on the client side when rendering LaTeX.
    // The database just contains the raw LaTeX like $$ x = y $$.
    // Let's search for some common LaTeX errors we know KaTeX/MathJax fails on based on our previous discussions,
    // or unescaped percentages in math blocks.
    
    let hasError = false;
    let issues = [];
    
    // Check for unescaped % in math blocks
    const blockRegex = /\$\$([\s\S]*?)\$\$/g;
    let match;
    while ((match = blockRegex.exec(body)) !== null) {
      if (match[1].match(/(?<!\\)%/)) {
        hasError = true;
        issues.push(`Unescaped '%' found in $$ block: ${match[1].substring(0, 30)}...`);
      }
      if (match[1].includes('&') && !match[1].includes('align') && !match[1].includes('bmatrix') && !match[1].includes('pmatrix') && !match[1].includes('matrix') && !match[1].includes('cases') && !match[1].includes('array')) {
         hasError = true;
         issues.push(`Misplaced '&' outside alignment environment: ${match[1].substring(0, 30)}...`);
      }
    }
    
    const inlineRegex = /(?<!\$)\$([^$\n]+)\$(?!\$)/g;
    while ((match = inlineRegex.exec(body)) !== null) {
      if (match[1].match(/(?<!\\)%/)) {
        hasError = true;
        issues.push(`Unescaped '%' found in $ block: ${match[1].substring(0, 30)}...`);
      }
    }
    
    if (hasError) {
      foundErrors = true;
      console.log(`\n========================================`);
      console.log(`Found potential LaTeX errors in:`);
      console.log(`Subject: ${data.subject}`);
      console.log(`Chapter: ${data.chapter}`);
      console.log(`Issues:`);
      issues.forEach(i => console.log(`  - ${i}`));
    }
  });
  
  if (!foundErrors) {
    console.log("No common structural LaTeX errors (like unescaped % or stray &) found in the Question Bank source code.");
  }
  
  process.exit(0);
}

run().catch(console.error);
